### ISSUE TITLE
Unknown property 'callId' on class 'class com.voxeo.tropo.TropoResult'

### ISSUE THREAD

**Issue by timr** [tropo/tropo-webapi-java#14]
We began receiving this exception using the library.
```
Caused by: net.sf.json.JSONException: java.lang.NoSuchMethodException: Unknown property 'callId' on class 'class com.voxeo.tropo.TropoResult'
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy._setProperty(PropertySetStrategy.java:69) ~[json-lib-2.4-jdk15.jar!/:na]
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy.setProperty(PropertySetStrategy.java:60) ~[json-lib-2.4-jdk15.jar!/:na]
	at net.sf.json.JSONObject.setProperty(JSONObject.java:1394) ~[json-lib-2.4-jdk15.jar!/:na]
	at net.sf.json.JSONObject.toBean(JSONObject.java:453) ~[json-lib-2.4-jdk15.jar!/:na]
	at net.sf.json.JSONObject.toBean(JSONObject.java:233) ~[json-lib-2.4-jdk15.jar!/:na]
	at com.voxeo.tropo.TropoParser.parse(TropoParser.java:84) ~[tropo-webapi-java-0.3.2.jar!/:na]
	... 51 common frames omitted
Caused by: java.lang.NoSuchMethodException: Unknown property 'callId' on class 'class com.voxeo.tropo.TropoResult'
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2123) ~[commons-beanutils-1.8.0.jar!/:1.8.0]
	at org.apache.commons.beanutils.PropertyUtils.setSimpleProperty(PropertyUtils.java:890) ~[commons-beanutils-1.8.0.jar!/:1.8.0]
	at net.sf.json.util.PropertySetStrategy$DefaultPropertySetStrategy._setProperty(PropertySetStrategy.java:67) ~[json-lib-2.4-jdk15.jar!/:na]
	... 56 common frames omitted
```

Here's an example of the request Tropo makes. I've slightly altered some of the fields.
```
{  
   "result":{  
      "sessionId":"3ff6c04bf17f711ec48ff499ea04def",
      "callId":"efec8f01fcce9da21924576fc0521ea",
      "state":"ANSWERED",
      "sessionDuration":51,
      "sequence":3,
      "complete":false,
      "error":null,
      "calledid":"+REMOVED",
      "actions":{  
         "name":"pin",
         "attempts":1,
         "disposition":"TIMEOUT"
      }
   }
}
```

**Comment by hemantsonu20** [comment]
I opened a pull request fixing this issue.

**Comment by mpermar** [comment]
Merged. Thanks @hemantsonu20!
